# This is a basic workflow to help you get started with Actions

on: [push, pull_request]
name: Test
jobs:
  exakat:
    name: Exakat Scanner
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Exakat
      uses: docker://exakat/exakat-ga
      with:
        ignore_rules: 'toto,%+&,Classes/StaticMethodsCalledFromObject'
        ignore_dirs: '/src/Sculpin/Test,/src/Sculpin/Core,/src/Sculpin/Contrib,/src/Sculpin/Bundle'
        project_reports: "Sarif"
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to SARIF file relative to the root of the repository
        #Full path : /usr/src/exakat/projects/review/code/exakat.sarif
        sarif_file: exakat.sarif
